# Setting Lakes for Shetran

This notebook was created to demostrate the process of creating the lakes use in SHETRAN based in the catchment extent

---

#### Author: 
                LF Velasquez & I Rohrmueller - Newcastle University

#### Date:
                Nov 2022

#### Version:
                1.0

#### Notes:
                - To get jupyter env version type `!jupyter --version` in a python cell
            
#### Jupyter version:

#### Python version:

---

# Notebook set-up

## 1. Setting Python Modules

In [7]:
import geopandas as gpd
import pandas as pd
from shapely.geometry import Polygon
import numpy as np
from pathlib import Path

# Custom modules
import utils

# Modules for config.ini
from configparser import ConfigParser
config = ConfigParser()

## 2. Global variables

In [8]:
# Setting the path to the work environment
dir_abs = Path().resolve().parent.parent
dir_abs

# Read config file values
config.read('config.ini')

# Setting CRS
crs_global = config.getint('crs_setting', 'GLB')
crs_local = config.getint('crs_setting', 'COL')

# No data value
ND = config.getint('res_setting', 'NO_DATA')

## 3. Start of Process

#### Create functions needed

In [9]:
def grid_latlon(soil_grid_df, crs_num):
    # Get the centroid for each grid
    temp_df = pd.DataFrame()
    temp_df = soil_grid_df.to_crs(crs_num)
    temp_df['centroid'] = temp_df['geometry'].centroid

    # Create lat (Y) and lon (X) columns
    temp_df['lat'] = temp_df['centroid'].y.astype(int)
    temp_df['lon'] = temp_df['centroid'].x.astype(int)

    # # Return the columns needed
    # df_grid = pd.DataFrame(temp_df[['lat', 'lon', 'geometry']].copy())

    
    return temp_df

### Reading shapefiles - mask and lakes dataset

In [10]:
# Read shp file to geopandas dataframe
grid_path = Path(dir_abs / 'shetran_data/active_data/final_mask_wgs84.shp')
grid = gpd.read_file(grid_path)

lakes_path = Path(dir_abs / 'shetran_data/active_data/HydroLAKES_polys_v10.shp')
lakes = gpd.read_file(lakes_path)

display(lakes)
display(grid)

,Hylak_id,Lake_name,Country,Continent,Poly_src,Lake_type,Grand_id,Lake_area,Shore_len,Shore_dev,...,Vol_src,Depth_avg,Dis_avg,Res_time,Elevation,Slope_100,Wshd_area,Pour_long,Pour_lat,geometry
0,1,Caspian Sea,Russia,Europe,SWBD,1,0,377001.91,15829.37,7.27,...,1,200.5,8110.642,107883.0,-29,-1.00,1404108.0,47.717708,45.591934,"POLYGON ((49.96181 37.43847, 49.96457 37.44022..."
1,2,Great Bear,Canada,North America,CanVec,1,0,30450.64,5331.72,8.62,...,1,72.2,535.187,47577.7,145,-1.00,147665.4,-123.505546,65.138384,"POLYGON ((-119.78782 67.03574, -119.78637 67.0..."
2,3,Great Slave,Canada,North America,CanVec,1,0,26734.29,9814.16,16.93,...,1,59.1,4350.692,4203.2,148,-1.00,995312.3,-117.617115,61.311727,"POLYGON ((-109.93976 62.95851, -109.93831 62.9..."
3,4,Winnipeg,Canada,North America,CanVec,3,709,23923.04,4018.32,7.33,...,1,11.9,2244.727,1464.3,215,-1.00,919611.5,-97.863542,53.696359,"POLYGON ((-98.80636 53.88021, -98.80578 53.880..."
4,5,Superior,United States of America,North America,SWBD,1,0,81843.92,5248.36,5.18,...,1,146.7,2869.953,48410.3,179,-1.00,209219.5,-84.460547,46.468593,"POLYGON ((-90.72250 46.65740, -90.72458 46.657..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1427683,1427684,None,New Zealand,Oceania,SWBD,1,0,0.29,2.30,1.20,...,3,5.1,0.125,139.6,1,4.83,4.4,169.147152,-52.592307,"POLYGON ((169.14763 -52.59291, 169.14750 -52.5..."
1427684,1427685,None,Australia,Oceania,SWBD,1,0,0.10,1.66,1.52,...,3,2.1,-9999.000,-9999.0,1,1.04,-9999.0,73.305108,-52.973622,"POLYGON ((73.30605 -52.97318, 73.30540 -52.974..."
1427685,1427686,None,Australia,Oceania,SWBD,1,0,0.24,1.92,1.10,...,3,3.7,0.013,792.4,205,2.63,0.2,158.892278,-54.529970,"POLYGON ((158.89124 -54.53117, 158.88696 -54.5..."
1427686,1427687,None,Australia,Oceania,SWBD,1,0,0.34,2.95,1.44,...,3,6.5,0.020,1263.9,163,7.58,0.4,158.889583,-54.594300,"POLYGON ((158.88858 -54.59767, 158.88833 -54.5..."
1427687,1427688,None,Australia,Oceania,SWBD,1,0,0.44,3.06,1.30,...,3,6.4,0.073,452.1,187,6.77,1.4,158.835417,-54.686534,"POLYGON ((158.83901 -54.68744, 158.83867 -54.6..."

     intersect  SHETRAN_ID                                           geometry
0            0       -9999  POLYGON ((-76.70463 3.59102, -76.68665 3.59107...
1            0       -9999  POLYGON ((-76.70458 3.57295, -76.68660 3.57300...
2            0       -9999  POLYGON ((-76.70453 3.55488, -76.68655 3.55493...
3            0       -9999  POLYGON ((-76.70448 3.53681, -76.68650 3.53687...
4            0       -9999  POLYGON ((-76.70443 3.51875, -76.68644 3.51880...
..         ...         ...                                                ...
793          1           0  POLYGON ((-76.03853 3.30348, -76.02054 3.30351...
794          0       -9999  POLYGON ((-76.03849 3.28540, -76.02051 3.28544...
795          0       -9999  POLYGON ((-76.03846 3.26733, -76.02047 3.26736...
796          0       -9999  POLYGON ((-76.03842 3.24925, -76.02044 3.24929...
797          0       -9999  POLYGON ((-76.03839 3.23117, -76.02040 3.23121...

[798 rows x 3 columns]

### Working with the grid and lakes to find which grids have lakes on them

In [11]:
# Intersect grid with lakes to find which grid has lakes
grid_lakes = gpd.sjoin(grid, lakes, how="left", predicate="intersects")


# Replace NaN with empty sting
grid_lakes = grid_lakes.replace(np.nan, '')


# Assing LAKE ID if value GLWD_ID is empty
grid_lakes["LAKE_ID"] = np.where(grid_lakes['Hylak_id'] == '', ND, 1)

# Create lat and lot values using the function
grid_centroids = grid_latlon(grid_lakes, crs_local)

# Change geopandas to pandas ready to create csv file
df_grid_lakes = pd.DataFrame(grid_centroids[['LAKE_ID', 'lat', 'lon']].copy())

# Remove duplicates just in case there is an error
df_grid_lakes = df_grid_lakes.drop_duplicates()

# Pivoting dataframe to replicate SHETRAN format
# Pivoting dataframe using lon as column and lat as row
df_pivot_grid_lakes = df_grid_lakes.pivot(index='lat', columns='lon', values='LAKE_ID')
df_pivot_grid_lakes = df_pivot_grid_lakes.sort_index(ascending=False)
df_pivot_grid_lakes

lon,709018,711018,713018,715018,717018,719018,721018,723018,725018,727018,...,765018,767018,769018,771018,773018,775018,777018,779018,781018,783018
lat,,,,,,,,,,,,,,,,,,,,,
888266,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,...,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999
886266,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,...,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999
884266,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,...,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999
882266,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,...,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999
880266,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,...,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999
878266,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,...,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999
876266,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,...,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,1,1
874266,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,...,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,1,1
872266,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,...,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999
870266,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,...,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999
868266,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,...,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999
866266,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,...,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999
864266,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,...,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999
862266,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,...,-9999,-9999,-9999,-9999,-9999,-9999,-9999,1,-9999,-9999
860266,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,...,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999
858266,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,...,-9999,-9999,-9999,-9999,-9999,-9999,-9999,1,-9999,-9999
856266,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,...,-9999,-9999,-9999,-9999,-9999,-9999,-9999,1,-9999,-9999
854266,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,...,-9999,-9999,-9999,-9999,-9999,-9999,-9999,1,-9999,-9999
852266,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,...,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,1
850266,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,...,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999
848266,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,...,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999

### Saving the final outpt as csv file

In [12]:
utils.shetran_csv_file(dir_abs, 'final_lake_map_SHETRAN', df_pivot_grid_lakes, 'd')
print('SHETRAN lake file created')

SHETRAN lake file created